/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'wrapped-pink': '#FF69B4',
        'wrapped-yellow': '#FFD700',
        'wrapped-green': '#98FB98',
        'wrapped-blue': '#87CEEB',
        'pastel-blue': '#A6D1E6',
        'invomagic-blue': '#2457ff',

        // Theme colors
        'theme-primary': 'var(--color-primary)',
        'theme-secondary': 'var(--color-secondary)',
        'theme-accent': 'var(--color-accent)',
        'theme-muted': 'var(--color-muted)',
        'theme-background': 'var(--color-background)',
        'theme-card': 'var(--color-card)',
        'theme-border': 'var(--color-border)',
      },
      fontFamily: {
        'saira': ['Saira', 'sans-serif'],
      },
      backgroundColor: {
        'dark-primary': '#121212',
        'dark-secondary': '#1e1e1e',
        'dark-card': '#2d2d2d',
      },
      textColor: {
        'dark-primary': '#ffffff',
        'dark-secondary': '#e0e0e0',
        'dark-muted': '#a0a0a0',
      },
      borderColor: {
        'dark-border': '#3d3d3d',
      },
      gradientColorStops: {
        'theme-gradient-start': 'var(--gradient-start)',
        'theme-gradient-middle': 'var(--gradient-middle)',
        'theme-gradient-end': 'var(--gradient-end)',
      },
      keyframes: {
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' }
        }
      },
      animation: {
        'slide-up': 'slide-up 0.3s ease-out forwards'
      }
    },
  },
  plugins: [
    function({ addBase }) {
      addBase({
        ':root': {
          // Default theme (pink)
          '--color-primary': '#FF69B4',
          '--color-secondary': '#f472b6',
          '--color-accent': '#FFD700',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#c94baf',
          '--gradient-middle': '#f472b6',
          '--gradient-end': '#a855f7',
        },
        '[data-color-scheme="blue"]': {
          '--color-primary': '#3B82F6',
          '--color-secondary': '#60a5fa',
          '--color-accent': '#34d399',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#1d4ed8',
          '--gradient-middle': '#3b82f6',
          '--gradient-end': '#93c5fd',
        },
        '[data-color-scheme="green"]': {
          '--color-primary': '#10B981',
          '--color-secondary': '#34d399',
          '--color-accent': '#f59e0b',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#059669',
          '--gradient-middle': '#10b981',
          '--gradient-end': '#6ee7b7',
        },
        '[data-color-scheme="purple"]': {
          '--color-primary': '#8B5CF6',
          '--color-secondary': '#a78bfa',
          '--color-accent': '#ec4899',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#6d28d9',
          '--gradient-middle': '#8b5cf6',
          '--gradient-end': '#c4b5fd',
        },
        '[data-color-scheme="cyberpunk"]': {
          '--color-primary': '#F59E0B',
          '--color-secondary': '#fbbf24',
          '--color-accent': '#ec4899',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#b45309',
          '--gradient-middle': '#f59e0b',
          '--gradient-end': '#fcd34d',
        },
        '[data-color-scheme="red"]': {
          '--color-primary': '#EF4444',
          '--color-secondary': '#f87171',
          '--color-accent': '#3B82F6',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#991b1b',
          '--gradient-middle': '#ef4444',
          '--gradient-end': '#fca5a5',
        },
        '[data-color-scheme="teal"]': {
          '--color-primary': '#14B8A6',
          '--color-secondary': '#2DD4BF',
          '--color-accent': '#F472B6',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#0F766E',
          '--gradient-middle': '#14B8A6',
          '--gradient-end': '#99F6E4',
        },
        '[data-color-scheme="orange"]': {
          '--color-primary': '#F97316',
          '--color-secondary': '#FB923C',
          '--color-accent': '#06B6D4',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#9A3412',
          '--gradient-middle': '#F97316',
          '--gradient-end': '#FDBA74',
        },
        '[data-color-scheme="rose"]': {
          '--color-primary': '#E11D48',
          '--color-secondary': '#FB7185',
          '--color-accent': '#22D3EE',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#9F1239',
          '--gradient-middle': '#E11D48',
          '--gradient-end': '#FDA4AF',
        },
        '[data-color-scheme="indigo"]': {
          '--color-primary': '#6366F1',
          '--color-secondary': '#818CF8',
          '--color-accent': '#F59E0B',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#4338CA',
          '--gradient-middle': '#6366F1',
          '--gradient-end': '#C7D2FE',
        },
        '[data-color-scheme="lime"]': {
          '--color-primary': '#84CC16',
          '--color-secondary': '#A3E635',
          '--color-accent': '#EC4899',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#4D7C0F',
          '--gradient-middle': '#84CC16',
          '--gradient-end': '#D9F99D',
        },
        '[data-color-scheme="amber"]': {
          '--color-primary': '#F59E0B',
          '--color-secondary': '#FBBF24',
          '--color-accent': '#06B6D4',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#B45309',
          '--gradient-middle': '#F59E0B',
          '--gradient-end': '#FDE68A',
        },
        '[data-color-scheme="sky"]': {
          '--color-primary': '#0EA5E9',
          '--color-secondary': '#38BDF8',
          '--color-accent': '#F472B6',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#0369A1',
          '--gradient-middle': '#0EA5E9',
          '--gradient-end': '#BAE6FD',
        },
        '[data-color-scheme="fuchsia"]': {
          '--color-primary': '#D946EF',
          '--color-secondary': '#E879F9',
          '--color-accent': '#22D3EE',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#A21CAF',
          '--gradient-middle': '#D946EF',
          '--gradient-end': '#F5D0FE',
        },
        '[data-color-scheme="brown"]': {
          '--color-primary': '#A78B71',
          '--color-secondary': '#C2A68D',
          '--color-accent': '#8B5E3C',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#8B5E3C',
          '--gradient-middle': '#A78B71',
          '--gradient-end': '#C2A68D',
        },
        '[data-color-scheme="gold"]': {
          '--color-primary': '#FFD700',
          '--color-secondary': '#FFC107',
          '--color-accent': '#FFB300',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#FFD700',
          '--gradient-middle': '#FFC107',
          '--gradient-end': '#FFB300',
        },
        '[data-color-scheme="silver"]': {
          '--color-primary': '#C0C0C0',
          '--color-secondary': '#B0B0B0',
          '--color-accent': '#A0A0A0',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#C0C0C0',
          '--gradient-middle': '#B0B0B0',
          '--gradient-end': '#A0A0A0',
        },
        '[data-color-scheme="bronze"]': {
          '--color-primary': '#CD7F32',
          '--color-secondary': '#D68A3A',
          '--color-accent': '#E09442',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#CD7F32',
          '--gradient-middle': '#D68A3A',
          '--gradient-end': '#E09442',
        },
        '[data-color-scheme="peach"]': {
          '--color-primary': '#FFDAB9',
          '--color-secondary': '#FFCBA4',
          '--color-accent': '#FFBC8F',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#FFDAB9',
          '--gradient-middle': '#FFCBA4',
          '--gradient-end': '#FFBC8F',
        },
        '[data-color-scheme="mint"]': {
          '--color-primary': '#98FF98',
          '--color-secondary': '#8FEF8F',
          '--color-accent': '#86DF86',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#98FF98',
          '--gradient-middle': '#8FEF8F',
          '--gradient-end': '#86DF86',
        },
        '[data-color-scheme="ruby"]': {
          '--color-primary': '#E0115F',
          '--color-secondary': '#FF1493',
          '--color-accent': '#FF69B4',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#B22222',
          '--gradient-middle': '#E0115F',
          '--gradient-end': '#FF69B4',
        },
        '[data-color-scheme="sapphire"]': {
          '--color-primary': '#0F52BA',
          '--color-secondary': '#4682B4',
          '--color-accent': '#87CEEB',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#1E90FF',
          '--gradient-middle': '#0F52BA',
          '--gradient-end': '#4682B4',
        },
        '[data-color-scheme="emerald"]': {
          '--color-primary': '#50C878',
          '--color-secondary': '#3CB371',
          '--color-accent': '#2E8B57',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#2E8B57',
          '--gradient-middle': '#50C878',
          '--gradient-end': '#3CB371',
        },
        '[data-color-scheme="topaz"]': {
          '--color-primary': '#FFC87C',
          '--color-secondary': '#FFB347',
          '--color-accent': '#FFA500',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#FFB347',
          '--gradient-middle': '#FFC87C',
          '--gradient-end': '#FFA500',
        },
        '[data-color-scheme="aquamarine"]': {
          '--color-primary': '#7FFFD4',
          '--color-secondary': '#76EEC6',
          '--color-accent': '#66CDAA',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#7FFFD4',
          '--gradient-middle': '#76EEC6',
          '--gradient-end': '#66CDAA',
        },
        '[data-color-scheme="coral"]': {
          '--color-primary': '#FF7F50',
          '--color-secondary': '#FF6347',
          '--color-accent': '#FF4500',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#FF7F50',
          '--gradient-middle': '#FF6347',
          '--gradient-end': '#FF4500',
        },
        '[data-color-scheme="lavender"]': {
          '--color-primary': '#E6E6FA',
          '--color-secondary': '#D8BFD8',
          '--color-accent': '#DDA0DD',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#E6E6FA',
          '--gradient-middle': '#D8BFD8',
          '--gradient-end': '#DDA0DD',
        },
        '[data-color-scheme="cyan"]': {
          '--color-primary': '#00BCD4',
          '--color-secondary': '#26C6DA',
          '--color-accent': '#E879F9',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#0097A7',
          '--gradient-middle': '#00BCD4',
          '--gradient-end': '#80DEEA',
        },
        '[data-color-scheme="peridot"]': {
          '--color-primary': '#E6E200',
          '--color-secondary': '#D4D700',
          '--color-accent': '#C4C400',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#E6E200',
          '--gradient-middle': '#D4D700',
          '--gradient-end': '#C4C400',
        },
        '[data-color-scheme="amethyst"]': {
          '--color-primary': '#9966CC',
          '--color-secondary': '#8A2BE2',
          '--color-accent': '#9370DB',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#9966CC',
          '--gradient-middle': '#8A2BE2',
          '--gradient-end': '#9370DB',
        },
        '[data-color-scheme="electricblue"]': {
          '--color-primary': '#1F53FF',
          '--color-secondary': '#4D75FF',
          '--color-accent': '#00CCFF',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': '#0033CC',
          '--gradient-middle': '#1F53FF',
          '--gradient-end': '#99BBFF',
        },
        '[data-color-scheme="custom"]': {
          '--color-primary': 'var(--custom-primary)',
          '--color-secondary': 'var(--custom-secondary)',
          '--color-accent': 'var(--custom-accent)',
          '--color-muted': '#9ca3af',
          '--color-background': '#f3f4f6',
          '--color-card': '#ffffff',
          '--color-border': '#e5e7eb',
          '--gradient-start': 'var(--custom-primary)',
          '--gradient-middle': 'var(--custom-secondary)',
          '--gradient-end': 'var(--custom-accent)',
        },
      });
    },
  ],
}
